POST http://localhost:3000/ideas/2/upvote
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZW1pbGlhIiwiaWF0IjoxNzE2MDUxODczLCJleHAiOjE3MTYxMzgyNzN9.-uYMdJO42whbxJlirRxBDyizsZRfKEa7XwiAs7ZFfv0

{
  
}

